246-configure-the-package-itself
StockwatchDev/application_settings pull request #263
Opened 2024-11-08 21:55 UTC by tjadevries

2025-01-10 15:57 UTC, JJdeVries requested changes

2025-01-10 15:57 UTC, JJdeVries commented on src/application_settings/container_base.py
> +        logger.log(
So it might be a bit dirty, but could we not work around the circular imports by doing the import just before this line? so change it to:
```
# import here to avoid a circular import between container_base and parameterization
from application_settings.parametrization import log_level
logger.log(
   ...
```

it's a bit dirty, but would allow us to make the `ApplicationSettingsContainerSectionBase` regular inherit from the base class

2025-01-10 15:57 UTC, JJdeVries commented on src/application_settings/container_section_base.py
> +                )
These warnings are really nice!

the library is becoming quite hard to follow though. probably also because i'm not putting in the work :-).

2025-01-10 15:57 UTC, JJdeVries commented on src/application_settings/parametrization.py
> +        return "WARNING" if ApplicationConfigSection.get().strict_mode else "DEBUG"
Unexpected that we're returning strings here. Is there not some proper log level enum?

2025-01-10 15:57 UTC, JJdeVries commented on src/application_settings/parametrization.py
> +        return "WARNING" if ApplicationConfigSection.get().strict_mode else "DEBUG"
hmm seems not in logaru, only integers are possible, so let's keep it like this.

2025-01-10 21:11 UTC, tjadevries commented on src/application_settings/parametrization.py
> +        return "WARNING" if ApplicationConfigSection.get().strict_mode else "DEBUG"
Okay.

2025-01-10 21:58 UTC, tjadevries commented on src/application_settings/container_section_base.py
> +                )
I added a bunch of comments, hopefully that makes it easier to understand.

Would like to know which other parts you find hard to follow...

2025-01-10 22:09 UTC, tjadevries commented on src/application_settings/container_base.py
> +        logger.log(
The price of the current solution is some code duplication. The code in parametrization.py is somewhat simpler, because these sections will not have subsections and we know for sure they are decorated.

I doubt whether doing this would resolve the circular imports. Moreover, I foresee that more fields will be added to e.g. ApplicationConfigSection and changes are that then the trick won't do. So if you don't mind, I'd like to go for a robust solution and pay the price of code duplication here. Can you agree?

2025-01-16 14:09 UTC, JJdeVries commented on src/application_settings/container_base.py
> +        logger.log(
Makes sense, this is only the first part of configuration of course. so yes let's do it.

Also immediately a use-case for the Protocol vs BaseClass :-).

2025-01-16 14:10 UTC, JJdeVries approved these changes

2025-01-16 18:05 UTC, tjadevries commented
Thanks @JJdeVries !

2025-01-16 18:06 UTC, merged